pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // سحب الكود من GitHub مع تحديد الفرع وبيانات الاعتماد
                git branch: 'main', 
                    url: 'https://github.com/alaametwale/alx-backend-python.git', 
                    credentialsId: 'my-github-credentials'  // <-- ضع هنا الـ ID الخاص ببيانات اعتماد GitHub
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest messaging_app/messaging_app/tests --junitxml=report.xml'
            }
        }

        stage('Archive Report') {
            steps {
                archiveArtifacts artifacts: 'report.xml', allowEmptyArchive: true
            }
        }
    }
}
